# Generated by Django 5.1.6 on 2025-03-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_roll_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='class_field',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school',
            field=models.CharField(blank=True, choices=[('school_1', 'School 1'), ('school_2', 'School 2'), ('school_3', 'School 3'), ('school_4', 'School 4'), ('school_5', 'School 5')], max_length=255, null=True),
        ),
    ]
