# Generated by Django 5.1.6 on 2025-04-14 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
