# Generated by Django 5.1.6 on 2025-04-15 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_delete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='delete',
        ),
    ]
