# Generated by Django 5.1.6 on 2025-04-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='admin_id',
            field=models.IntegerField(default=14),
        ),
    ]
